import React, { useCallback, useEffect, useState } from 'react';
import { apiGet, apiPost } from '../services/api';
import { EmptyState, ErrorState, LoadingState } from './ui/PageState';

type Promotion = { id:string; title:string; description:string|null; status:string; startsAt:string; expiresAt:string };
const date = (value:string) => new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));

export default function Promotions() {
  const [items,setItems]=useState<Promotion[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[title,setTitle]=useState(''),[creating,setCreating]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{setItems((await apiGet<{promotions:Promotion[]}>('/api/promotions')).promotions);setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar promoções.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();setCreating(true);try{const now=Date.now();await apiPost('/api/promotions',{title,startsAt:new Date(now).toISOString(),expiresAt:new Date(now+86400000).toISOString(),status:'active'});setTitle('');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível publicar.')}finally{setCreating(false)}};
  return <main className="mavo-page"><div className="mavo-page-content"><div className="mb-7"><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Comercial</p><h2 className="mt-1 text-2xl font-black text-slate-900 dark:text-white">Promoções</h2><p className="mt-2 text-slate-500">Publique uma oferta com validade padrão de 24 horas.</p></div><form onSubmit={create} className="mavo-card mb-5 flex flex-wrap gap-3 p-4"><label className="min-w-56 flex-1 text-sm font-bold">Título da oferta<input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)} className="mavo-field mt-1" placeholder="Ex.: Ofertas da semana"/></label><button disabled={creating} className="mavo-button-primary self-end">{creating?'Publicando…':'Publicar 24h'}</button></form>{loading?<LoadingState title="Carregando promoções…"/>:error?<ErrorState title="Não foi possível carregar promoções" description={error} action={<button onClick={()=>void load()} className="mavo-button-secondary">Tentar novamente</button>}/>:items.length===0?<EmptyState title="Nenhuma promoção cadastrada" description="Crie a primeira oferta para disponibilizá-la ao bot."/>:<div className="space-y-3">{items.map(item=><article key={item.id} className="mavo-card p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black text-slate-900 dark:text-white">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.description||'Sem descrição.'}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{item.status}</span></div><p className="mt-3 text-xs text-slate-500">Válida de {date(item.startsAt)} até {date(item.expiresAt)}</p></article>)}</div>}</div></main>;
}
